{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx # for ingress-nginx controller
  rules:
    - host: app.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              serviceName: {{ include "chart.fullname" . }}
              servicePort: 5000
          - path: /.*
            pathType: Prefix
            backend:
              serviceName: {{ include "chart.fullname" . }}
              servicePort: 3000
{{- end -}}